Option Explicit

Sub CreateSimpleCube()
    Dim swApp As SldWorks.SldWorks
    Dim swModel As SldWorks.ModelDoc2
    Dim swSketchMgr As SldWorks.SketchManager
    Dim cubeSize As Double
    
    ' Set cube size (in meters)
    cubeSize = 0.1 ' 100mm cube
    
    ' Connect to SolidWorks
    Set swApp = Application.SldWorks
    
    ' Create new part
    Set swModel = swApp.NewPart()
    
    ' Create sketch on front plane
    Set swSketchMgr = swModel.SketchManager
    swModel.SketchManager.InsertSketch True
    
    ' Draw center rectangle
    swSketchMgr.CreateCenterRectangle 0, 0, 0, cubeSize/2, cubeSize/2, 0
    
    ' Exit sketch
    swModel.InsertSketch2 True
    
    ' Extrude to create cube
    swModel.FeatureManager.FeatureExtrusion2 _
        True, False, False, 0, 0, cubeSize, 0.01, _
        False, False, False, False, 0, 0, _
        False, False, False, False, True, True, True, _
        0, 0, False
    
    ' Zoom to fit
    swModel.ViewZoomtofit2
    
    ' Clean up
    Set swSketchMgr = Nothing
    Set swModel = Nothing
    Set swApp = Nothing
    
    MsgBox "Cube created successfully!", vbInformation, "Done"
End Sub
